version: "3.8"

networks:
  uaifood-network:

volumes:
  uaifood_postgres_data:
    name: uaifood_postgres_data
services:
  uaifood_postgres:
    container_name: uaifood_postgres
    image: postgres:11-alpine
    restart: always
    env_file: .env
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - uaifood_postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_NAME

