version: "3.8"

networks:
  uaifood-network:

volumes:
  uaifood_db_data:
    name: uaifood_db_data
services:
  uaifood-mongodb:
    container_name: uaifood-mongodb
    image: mongo:4.2
    restart: always
    ports:
      - $MONGODB_PORT:27017
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_NAME
    networks:
      - uaifood-network
    volumes:
      - uaifood_db_data:/data/db
      - ./scripts/mongo/001_users.sh:/docker-entrypoint-initdb.d/001_users.sh:ro

