export const errorAlias = {
  FATAL_ERROR: 'FATAL ERROR',
  UNKNOWN: 'UNKNOWN',
  UNHANDLED_HTTP_REJECTION: 'UNHANDLED_HTTP_REJECTION',
  UNHANDLED_REJECTION: 'UNHANDLED_REJECTION',
  INVALID_MONGO_ID: 'INVALID_MONGO_ID',
};
